# This file is part of REANA.
# Copyright (C) 2017, 2018, 2019, 2020 CERN.
#
# REANA is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

notifications:
  email: false

sudo: true

language: python

cache:
  - pip

python:
  - "3.6"

services:
  - docker

before_install:
  - pip install -r requirements.txt
  - travis_retry pip install --upgrade pip setuptools py
  - travis_retry pip install twine wheel coveralls

install:
  - travis_retry pip install -e .[all]

script:
  - ./run-tests.sh

after_success:
  - coveralls
